version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./Demo_UpWebShell/Uploads:/inetpub/wwwroot/Uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped 